apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: flask-ingress
  namespace: flask
  annotations:
spec:
  rules:
  - host: one.flask.svc.cluster.local
    http:
      paths:
      - path: /reverse
        backend:
          serviceName: flask-reverse
          servicePort: 5000
      - path: /api
        backend:
          serviceName: flask-api
          servicePort: 5000
      - path: /random
        backend:
          serviceName: flask-api
          servicePort: 5000
