apiVersion: v1
kind: Service
metadata:
  name: flask-reverse
  namespace: flask
  labels:
    service: flask-reverse
spec:
  selector:
    app: flask-reverse
  ports:
  - port: 5000
    targetPort: 5000

