apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flask-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      containers:
      - name: flask-api
        image: localhost:5001/flask-api:latest
        ports:
        - containerPort: 5000
        imagePullPolicy: "Always"
      restartPolicy: "Always"
